Write-Output "Publishing AdventureWorks2017"
& sqlpackage.exe -SourceFile:"..\Databases\AdventureWorks2017\AdventureWorks2017\bin\Debug\AdventureWorks2017.dacpac" -Action:Publish -TargetDatabaseName:"AdventureWorks2017" -TargetServerName:"."
Write-Output "Publishing StackOverflow"
& sqlpackage.exe -SourceFile:"..\Databases\StackOverflow2010\StackOverflow2010\bin\Debug\StackOverflow2010.dacpac" -Action:Publish -TargetDatabaseName:"StackOverflow2010" -TargetServerName:"."
# Write-Output "Publishing WorldWideImporters"
# & sqlpackage.exe -SourceFile:"..\Databases\WorldWideImporters\WorldWideImporters\bin\Debug\WorldWideImporters.dacpac" -Action:Publish -TargetDatabaseName:"WorldWideImporters" -TargetServerName:"."